name: Run React Frontend Tests

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Run Unit Tests
        run: npm test -- --watchAll=false
